name: Build XCFramework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install autotools
      run: |
        brew install autoconf automake libtool

    - name: Setup build environment
      run: |
        aclocal && autoconf && automake --add-missing
        mkdir -p "$OUTPUT_DIR"

    - name: Build for macOS arm64
      run: |
        ./build_library.sh macosx arm64 MacOSX

    - name: Build for macOS x86_64
      run: |
        ./build_library.sh macosx x86_64 MacOSX

    - name: Build for iOS arm64
      run: |
        ./build_library.sh iphoneos arm64 iPhoneOS

    - name: Build for iOS Simulator x86_64
      run: |
        ./build_library.sh iphonesimulator x86_64 iPhoneSimulator

    - name: Build for iOS Simulator arm64
      run: |
        ./build_library.sh iphonesimulator arm64 iPhoneSimulator

    - name: Create XCFrameworks
      run: |
        mkdir -p "${OUTPUT_DIR}/Headers/"
        
        rm -rf ${OUTPUT_DIR}/Headers/*
        rm -rf ${OUTPUT_DIR}/opencore-amrnb.xcframework
        cp -a amrnb/{interf_dec,interf_enc}.h ${OUTPUT_DIR}/Headers/
        ./create_xcframework.sh opencore-amrnb
        
        rm -rf ${OUTPUT_DIR}/Headers/*
        rm -rf ${OUTPUT_DIR}/opencore-amrwb.xcframework
        cp -a amrwb/{dec_if,if_rom}.h ${OUTPUT_DIR}/Headers/
        ./create_xcframework.sh opencore-amrwb

    - name: Upload XCFrameworks
      uses: actions/upload-artifact@v2
      with:
        name: XCFrameworks
        path: ${{ env.OUTPUT_DIR }}/*.xcframework
